# Generated by https://quicktype.io


class PastePy:
    user_id: int
    id: int
    title: str
    body: str

    def __init__(self, user_id: int, id: int, title: str, body: str) -> None:
        self.user_id = user_id
        self.id = id
        self.title = title
        self.body = body
